### ISSUE TITLE
有一个小错误

### ISSUE THREAD

**Issue by gofinal** [AllenCoder/BRVAH_kotlin#2]
homeAdapter.onItemClickListener = BaseQuickAdapter.OnItemClickListener { adapter, view, position ->
            val intent = Intent(this@HomeActivity, ACTIVITY[position])
            startActivity(intent)
            startActivity<HomeActivity>()
        }

这里有个错误啊 ,点击item的时候 又启动了一次 HomeActivity

**Comment by typebrook** [comment]
https://github.com/AllenCoder/BRVAH_kotlin/blob/8cf1e1d67ddcd7f14f42482164471d84382ec1a6/app/src/main/java/com/allen/kotlinapp/HomeActivity.kt#L47

Line needs to delete @AllenCoder

**Comment by AllenCoder** [comment]
Thank you ! I will fix it
